
name: Deploy Rust Python Objects Book
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install mdbook
      run: |
        mkdir mdbook
        curl -Lf https://github.com/rust-lang/mdBook/releases/download/v0.4.15/mdbook-v0.4.15-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH

    - name: deploy book
      run: |
        git checkout gh-pages
        git checkout main "book/src/*" "book/book.toml"
        rm -rf src
        mv ./book/book.toml ./book/src .
        rm -rf book
        mdbook build
        git add .
        git commit -m "rust book built ($GITHUB_SHA) automatically and deployed to gh-pages"
        git push github gh-pages
        echo -e "\n\ndeployed book with code=0"